name: 部署並自動測試 SchedulerAgent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 檢出原始碼
      - name: 取得原始碼
        uses: actions/checkout@v4

      # 2. 設定 Python 3.11
      - name: 設定 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. 安裝依賴套件（本地測試用）
      - name: 安裝依賴套件
        run: |
          pip install -r SchedulerAgent_function/requirements.txt

      # 4. 登入 Azure
      - name: 登入 Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 5. 部署至 Azure Functions
      - name: 發佈至 Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: SchedulerAgent_function

      # 6. 等待部署完成
      - name: 等待部署完成
        run: sleep 30

      # 7. 安裝 requests 套件（執行測試腳本用）
      - name: 安裝 requests 套件
        run: pip install requests

      # 8. 執行健康檢查自動化測試
      - name: 執行健康檢查自動化測試
        env:
          AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        run: |
          python tests/test_health_endpoint.py
