name: Deploy SchedulerAgent Function App

on:
  push:
    branches: [ "main" ]
    paths:
      - "SchedulerAgent_function/**"
      - ".github/workflows/deploy.yml"
      - "requirements.txt"
  workflow_dispatch:

permissions:
  id-token: write     # ✅ OIDC token for azure/login
  contents: read

env:
  PYTHON_VERSION: "3.11"
  AZURE_FUNCTIONAPP_NAME: "SchedulerAgent"         # ← 這裡改成你的 Function App 名稱
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "SchedulerAgent_function" # 你的函式程式碼根目錄
  REQUIREMENTS_FILE: "SchedulerAgent_function/requirements.txt"

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies (into .python_packages)
        run: |
          python -m pip install --upgrade pip
          pip install -r "${{ env.REQUIREMENTS_FILE }}" --target "./.python_packages/lib/site-packages"

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show Azure context (debug)
        run: |
          echo "=== az account show ==="
          az account show
          echo "=== az account list (table) ==="
          az account list --output table

      # 若你需要先建立儲存體、App 設定等，可在此加入 az CLI 步驟

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          # slot-name: 'Production'  # 如有 slot 再開啟
